# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: fd1ab41
_src_path: git@github.com:vivienm/copier-copier
author_name: Vivien Maisonneuve
copyright_holder: Vivien Maisonneuve
copyright_year: 2023
github_account: vivienm
hosting_platform: github
license: MIT
project_description: An opinionated Copier template for Rust projects.
project_name: Rust project template
repo_name: copier-rust
