# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY.

_commit: 75951f1
_src_path: git@github.com:vivienm/copier-copier
copyright_holder: Vivien Maisonneuve
copyright_year: 2023
forge: github
github_repo: copier-rust
github_user: vivienm
license: MIT
project_description: An opinionated Copier template for Rust projects.
project_name: Rust project template
user_name: Vivien Maisonneuve
